# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  snapshot:
    cmds:
      - goreleaser release --snapshot --rm-dist
    silent: false

  check:
    desc: Check goreleaser config
    cmds:
      - goreleaser check