# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  snapshot:
    cmds:
      - goreleaser release --snapshot --rm-dist
    silent: false

  check:
    desc: Check goreleaser config
    cmds:
      - goreleaser check

  build:
    desc: local builg go
    cmds:
      - go build -o dist/isl main/main.go

  install:
    desc: install on mac
    deps: [build]
    cmds:
      - rm /usr/local/bin/isl
      - cp ./dist/isl /usr/local/bin/isl
